import type { BaseMetricCatalogEntry } from "../types/metric-definition.types.js";

export const BASE_METRIC_CATALOG: readonly BaseMetricCatalogEntry[] = [
  {
    key: "totalSku",
    name: "Total SKU",
    description: "Total products in the current filtered inventory scope.",
    scope: "organization",
    format: "number",
  },
  {
    key: "totalQuantity",
    name: "Total Quantity",
    description: "Total on-hand quantity in the current filtered inventory scope.",
    scope: "organization",
    format: "quantity",
  },
  {
    key: "totalValue",
    name: "Total Value",
    description: "Total inventory valuation in the current filtered scope.",
    scope: "organization",
    format: "currency",
  },
  {
    key: "criticalCount",
    name: "Critical Stock Count",
    description: "Count of products at or below the critical stock threshold.",
    scope: "organization",
    format: "number",
  },
  {
    key: "lowCount",
    name: "Low Stock Count",
    description: "Count of products between critical and low stock thresholds.",
    scope: "organization",
    format: "number",
  },
  {
    key: "movementCount",
    name: "Movement Count",
    description: "Total stock movement records in the current filtered scope.",
    scope: "organization",
    format: "number",
  },
  {
    key: "stockInQuantity",
    name: "Stock In Quantity",
    description: "Total inbound quantity from stock-in events.",
    scope: "organization",
    format: "quantity",
  },
  {
    key: "stockOutQuantity",
    name: "Stock Out Quantity",
    description: "Total outbound quantity from stock-out events.",
    scope: "organization",
    format: "quantity",
  },
  {
    key: "transferInQuantity",
    name: "Transfer In Quantity",
    description: "Total inbound quantity from transfer-in events.",
    scope: "organization",
    format: "quantity",
  },
  {
    key: "transferOutQuantity",
    name: "Transfer Out Quantity",
    description: "Total outbound quantity from transfer-out events.",
    scope: "organization",
    format: "quantity",
  },
  {
    key: "adjustmentIncreaseQuantity",
    name: "Adjustment Increase Quantity",
    description: "Total quantity added through manual adjustments.",
    scope: "organization",
    format: "quantity",
  },
  {
    key: "adjustmentDecreaseQuantity",
    name: "Adjustment Decrease Quantity",
    description: "Total quantity removed through manual adjustments.",
    scope: "organization",
    format: "quantity",
  },
  {
    key: "inboundQuantity",
    name: "Inbound Quantity",
    description: "Combined inbound quantity across stock-in, transfer-in, and adjustment increases.",
    scope: "organization",
    format: "quantity",
  },
  {
    key: "outboundQuantity",
    name: "Outbound Quantity",
    description: "Combined outbound quantity across stock-out, transfer-out, and adjustment decreases.",
    scope: "organization",
    format: "quantity",
  },
  {
    key: "netQuantity",
    name: "Net Quantity",
    description: "Inbound quantity minus outbound quantity for the current filtered scope.",
    scope: "organization",
    format: "quantity",
  },
] as const;

