-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN; -- Begin commit
-- Drop existing schema
DROP SCHEMA IF EXISTS auth CASCADE;
DROP SCHEMA IF EXISTS inventory CASCADE;
DROP SCHEMA IF EXISTS analytics CASCADE;
-- Create new schema from scratch.
CREATE SCHEMA IF NOT EXISTS auth
	AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS inventory
	AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS analytics
	AUTHORIZATION postgres;

COMMENT ON SCHEMA auth
    IS 'Authentication and access control schema for organizations, roles, permissions, and user accounts.';

COMMENT ON SCHEMA inventory
    IS 'Inventory domain schema for products, stock balances, and stock movement history.';

COMMENT ON SCHEMA analytics
    IS 'Analytics schema for organization-scoped custom metric definitions and future derived reporting models.';
-- Drop existing constraints for tables
ALTER TABLE IF EXISTS auth.accounts DROP CONSTRAINT IF EXISTS fk_role_id_accounts_id;

ALTER TABLE IF EXISTS auth.accounts DROP CONSTRAINT IF EXISTS fk_org_id_organizations_id;

ALTER TABLE IF EXISTS auth.role_permissions DROP CONSTRAINT IF EXISTS "References to role";

ALTER TABLE IF EXISTS auth.roles DROP CONSTRAINT IF EXISTS fk_org_id_organization_id;

ALTER TABLE IF EXISTS inventory.inventory DROP CONSTRAINT IF EXISTS fk_product_id_products_id;

ALTER TABLE IF EXISTS inventory.products DROP CONSTRAINT IF EXISTS fk_owner_id_organizations_id;

ALTER TABLE IF EXISTS inventory.stock_movements DROP CONSTRAINT IF EXISTS fk_owner_id_organizations_id;

ALTER TABLE IF EXISTS inventory.stock_movements DROP CONSTRAINT IF EXISTS fk_actor_id_accounts_id;

ALTER TABLE IF EXISTS inventory.stock_movements DROP CONSTRAINT IF EXISTS fk_product_id_products_id;


-- Drop and Create the table again from scratch
DROP TABLE IF EXISTS auth.accounts;

CREATE TABLE IF NOT EXISTS auth.accounts
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    org_id uuid NOT NULL,
    profile_url text COLLATE pg_catalog."default",
    profile_object_key text COLLATE pg_catalog."default",
    name text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default" NOT NULL,
    username text COLLATE pg_catalog."default" NOT NULL,
    auth_provider text COLLATE pg_catalog."default" NOT NULL DEFAULT 'backend',
    cognito_sub text COLLATE pg_catalog."default",
    password_hash text COLLATE pg_catalog."default",
    role_id uuid,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT accounts_pkey PRIMARY KEY (id),
    CONSTRAINT accounts_auth_provider_check CHECK (auth_provider IN ('backend', 'cognito')),
    CONSTRAINT accounts_auth_credential_check CHECK (
        (auth_provider = 'backend' AND password_hash IS NOT NULL)
        OR
        (auth_provider = 'cognito' AND cognito_sub IS NOT NULL)
    ),
    CONSTRAINT accounts_cognito_sub_key UNIQUE (cognito_sub),
    CONSTRAINT "Unique username" UNIQUE (username)
        INCLUDE(username)
);

COMMENT ON TABLE auth.accounts
    IS 'User account records for local or Cognito-based authentication, profile details, organization membership, and role assignment.';

DROP TABLE IF EXISTS auth.role_permissions;

CREATE TABLE IF NOT EXISTS auth.role_permissions
(
    role_id uuid NOT NULL,
    permission text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission)
);

COMMENT ON TABLE auth.role_permissions
    IS 'Permission assignments that define the actions available to each role.';

DROP TABLE IF EXISTS auth.roles;

CREATE TABLE IF NOT EXISTS auth.roles
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    org_id uuid NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    level smallint NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT unique_org_id_name UNIQUE (name, org_id),
    CONSTRAINT roles_level_check CHECK (level >= 0 AND level <= 255)
);

COMMENT ON TABLE auth.roles
    IS 'Role definitions used to group permissions within an organization.';

DROP TABLE IF EXISTS auth.organizations;

CREATE TABLE IF NOT EXISTS auth.organizations
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text,
    join_key text NOT NULL,
    critical_stock_threshold integer NOT NULL DEFAULT 10,
    low_stock_threshold integer NOT NULL DEFAULT 25,
    CONSTRAINT organizations_join_key_key UNIQUE (join_key),
    CONSTRAINT organizations_join_key_check CHECK (join_key ~ '^[A-Z0-9]{8}$'),
    CONSTRAINT organizations_threshold_check CHECK (critical_stock_threshold >= 0 AND low_stock_threshold >= critical_stock_threshold),
    PRIMARY KEY (id)
);

COMMENT ON TABLE auth.organizations
    IS 'Organization records that own accounts, roles, and inventory data.';

DROP TABLE IF EXISTS inventory.inventory;

CREATE TABLE IF NOT EXISTS inventory.inventory
(
    product_id uuid NOT NULL,
    quantity integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT inventory_pkey PRIMARY KEY (product_id)
);

COMMENT ON TABLE inventory.inventory
    IS 'Current on-hand stock quantity for each product.';

DROP TABLE IF EXISTS inventory.products;

CREATE TABLE IF NOT EXISTS inventory.products
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    owner_id uuid,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    sku text COLLATE pg_catalog."default",
    image_url text COLLATE pg_catalog."default",
    image_object_key text COLLATE pg_catalog."default",
    unit_cost numeric(12,2) NOT NULL DEFAULT 0,
    deleted_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT unique_sku UNIQUE (owner_id, sku)
        INCLUDE(sku)
);

COMMENT ON TABLE inventory.products
    IS 'Product catalog records tracked by the inventory system.';

DROP TABLE IF EXISTS inventory.stock_movements;

CREATE TABLE IF NOT EXISTS inventory.stock_movements
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    owner_id uuid NOT NULL,
    actor_id uuid,
    product_id uuid,
    product_name text COLLATE pg_catalog."default" NOT NULL,
    type text COLLATE pg_catalog."default" NOT NULL,
    quantity integer DEFAULT 0,
    reason text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT stock_movements_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE inventory.stock_movements
    IS 'Audit log of stock-in, stock-out, and other inventory quantity changes.';

DROP TABLE IF EXISTS analytics.metric_definitions;

DROP TABLE IF EXISTS analytics.alert_definitions;

CREATE TABLE IF NOT EXISTS analytics.metric_definitions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    org_id uuid NOT NULL,
    key text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    scope text COLLATE pg_catalog."default" NOT NULL DEFAULT 'organization',
    format text COLLATE pg_catalog."default" NOT NULL DEFAULT 'number',
    definition_json jsonb NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_by uuid NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT metric_definitions_pkey PRIMARY KEY (id),
    CONSTRAINT metric_definitions_org_key UNIQUE (org_id, key),
    CONSTRAINT metric_definitions_scope_check CHECK (scope IN ('organization', 'product', 'category')),
    CONSTRAINT metric_definitions_format_check CHECK (format IN ('number', 'percent', 'currency', 'quantity')),
    CONSTRAINT metric_definitions_definition_json_check CHECK (jsonb_typeof(definition_json) = 'object')
);

COMMENT ON TABLE analytics.metric_definitions
    IS 'Organization-scoped custom metric definitions stored as validated JSON expressions over base metrics.';

CREATE TABLE IF NOT EXISTS analytics.alert_definitions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    org_id uuid NOT NULL,
    key text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    severity text COLLATE pg_catalog."default" NOT NULL DEFAULT 'medium',
    scope text COLLATE pg_catalog."default" NOT NULL DEFAULT 'organization',
    condition_json jsonb NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_by uuid NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT alert_definitions_pkey PRIMARY KEY (id),
    CONSTRAINT alert_definitions_org_key UNIQUE (org_id, key),
    CONSTRAINT alert_definitions_severity_check CHECK (severity IN ('low', 'medium', 'high')),
    CONSTRAINT alert_definitions_scope_check CHECK (scope IN ('organization', 'product', 'category')),
    CONSTRAINT alert_definitions_condition_json_check CHECK (jsonb_typeof(condition_json) = 'object')
);

COMMENT ON TABLE analytics.alert_definitions
    IS 'Organization-scoped alert definition records stored as validated JSON conditions over base or custom metrics.';

ALTER TABLE IF EXISTS analytics.metric_definitions
    ADD CONSTRAINT fk_metric_definitions_org_id_organizations_id FOREIGN KEY (org_id)
    REFERENCES auth.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;

ALTER TABLE IF EXISTS analytics.metric_definitions
    ADD CONSTRAINT fk_metric_definitions_created_by_accounts_id FOREIGN KEY (created_by)
    REFERENCES auth.accounts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS analytics.alert_definitions
    ADD CONSTRAINT fk_alert_definitions_org_id_organizations_id FOREIGN KEY (org_id)
    REFERENCES auth.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;

ALTER TABLE IF EXISTS analytics.alert_definitions
    ADD CONSTRAINT fk_alert_definitions_created_by_accounts_id FOREIGN KEY (created_by)
    REFERENCES auth.accounts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS auth.accounts
    ADD CONSTRAINT fk_role_id_accounts_id FOREIGN KEY (role_id)
    REFERENCES auth.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS auth.accounts
    ADD CONSTRAINT fk_org_id_organizations_id FOREIGN KEY (org_id)
    REFERENCES auth.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS auth.role_permissions
    ADD CONSTRAINT "References to role" FOREIGN KEY (role_id)
    REFERENCES auth.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS auth.roles
    ADD CONSTRAINT fk_org_id_organization_id FOREIGN KEY (org_id)
    REFERENCES auth.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS inventory.inventory
    ADD CONSTRAINT fk_product_id_products_id FOREIGN KEY (product_id)
    REFERENCES inventory.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS inventory.products
    ADD CONSTRAINT fk_owner_id_organizations_id FOREIGN KEY (owner_id)
    REFERENCES auth.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS inventory.stock_movements
    ADD CONSTRAINT fk_owner_id_organizations_id FOREIGN KEY (owner_id)
    REFERENCES auth.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS inventory.stock_movements
    ADD CONSTRAINT fk_actor_id_accounts_id FOREIGN KEY (actor_id)
    REFERENCES auth.accounts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS inventory.stock_movements
    ADD CONSTRAINT fk_product_id_products_id FOREIGN KEY (product_id)
    REFERENCES inventory.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

COMMENT ON CONSTRAINT organizations_pkey ON auth.organizations
    IS 'Primary key for organizations.';

COMMENT ON CONSTRAINT roles_pkey ON auth.roles
    IS 'Primary key for roles.';

COMMENT ON CONSTRAINT role_permissions_pkey ON auth.role_permissions
    IS 'Composite primary key for role-permission mappings.';

COMMENT ON CONSTRAINT accounts_pkey ON auth.accounts
    IS 'Primary key for user accounts.';

COMMENT ON CONSTRAINT products_pkey ON inventory.products
    IS 'Primary key for products.';

COMMENT ON CONSTRAINT inventory_pkey ON inventory.inventory
    IS 'Primary key for inventory balances, using product_id.';

COMMENT ON CONSTRAINT stock_movements_pkey ON inventory.stock_movements
    IS 'Primary key for stock movement audit records.';

COMMENT ON CONSTRAINT fk_role_id_accounts_id ON auth.accounts
    IS 'Associates each account with its assigned role.';

COMMENT ON CONSTRAINT fk_org_id_organizations_id ON auth.accounts
    IS 'Associates each account with the organization it belongs to.';

COMMENT ON CONSTRAINT "References to role" ON auth.role_permissions
    IS 'Associates each role-permission mapping with its parent role.';

COMMENT ON CONSTRAINT fk_org_id_organization_id ON auth.roles
    IS 'Associates each role with the organization in which it is defined.';

COMMENT ON CONSTRAINT fk_product_id_products_id ON inventory.inventory
    IS 'Associates each inventory balance row with the product it tracks.';

COMMENT ON CONSTRAINT fk_owner_id_organizations_id ON inventory.products
    IS 'Associates each product with its owning organization.';

COMMENT ON CONSTRAINT fk_owner_id_organizations_id ON inventory.stock_movements
    IS 'Associates each stock movement record with its owning organization.';

COMMENT ON CONSTRAINT fk_actor_id_accounts_id ON inventory.stock_movements
    IS 'Associates each stock movement with the account that performed the action.';

COMMENT ON CONSTRAINT fk_product_id_products_id ON inventory.stock_movements
    IS 'Associates each stock movement with the product affected by the quantity change.';


-- Validate Auth Schema Constraints
ALTER TABLE analytics.metric_definitions VALIDATE CONSTRAINT fk_metric_definitions_org_id_organizations_id;
ALTER TABLE analytics.metric_definitions VALIDATE CONSTRAINT fk_metric_definitions_created_by_accounts_id;
ALTER TABLE analytics.alert_definitions VALIDATE CONSTRAINT fk_alert_definitions_org_id_organizations_id;
ALTER TABLE analytics.alert_definitions VALIDATE CONSTRAINT fk_alert_definitions_created_by_accounts_id;
ALTER TABLE auth.accounts VALIDATE CONSTRAINT fk_role_id_accounts_id;
ALTER TABLE auth.accounts VALIDATE CONSTRAINT fk_org_id_organizations_id;
ALTER TABLE auth.role_permissions VALIDATE CONSTRAINT "References to role";
ALTER TABLE auth.roles VALIDATE CONSTRAINT fk_org_id_organization_id;

-- Validate Inventory Schema Constraints
ALTER TABLE inventory.inventory VALIDATE CONSTRAINT fk_product_id_products_id;
ALTER TABLE inventory.products VALIDATE CONSTRAINT fk_owner_id_organizations_id;
ALTER TABLE inventory.stock_movements VALIDATE CONSTRAINT fk_owner_id_organizations_id;
ALTER TABLE inventory.stock_movements VALIDATE CONSTRAINT fk_actor_id_accounts_id;
ALTER TABLE inventory.stock_movements VALIDATE CONSTRAINT fk_product_id_products_id;

-- Commit it
END;
